"""Document Export — 純 CPU 文件格式轉換引擎.

將 HTML 或結構化內容轉換為 PDF / Word / PPT / Excel，零 token 消耗。

用法：
    from museon.tools.document_export import export_document

    # HTML → PDF
    path = export_document("pdf", html=html_string, title="報告")

    # 結構化內容 → Word
    path = export_document("docx", sections=[
        {"heading": "標題", "body": "內容..."},
    ], title="報告")

    # 表格資料 → Excel
    path = export_document("xlsx", tables=[
        {"name": "工作表1", "headers": ["A","B"], "rows": [[1,2],[3,4]]},
    ], title="報告")

    # 重點摘要 → PPT
    path = export_document("pptx", slides=[
        {"title": "第一頁", "bullets": ["重點1", "重點2"]},
    ], title="簡報")

    # 一鍵匯出 + 發佈到 GitHub Pages + 拿連結
    url = publish_document("pdf", html=html_string, title="報告")
    # → "https://zealchou.github.io/MUSEON/reports/報告_20260324_2150.pdf"
"""

import logging
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# 預設輸出目錄
_OUTPUT_DIR = Path(tempfile.gettempdir()) / "museon_exports"


def export_document(
    fmt: str,
    *,
    title: str = "MUSEON Document",
    html: str = "",
    sections: Optional[List[Dict[str, str]]] = None,
    tables: Optional[List[Dict[str, Any]]] = None,
    slides: Optional[List[Dict[str, Any]]] = None,
    output_dir: Optional[str] = None,
) -> str:
    """統一入口：將內容匯出為指定格式.

    Args:
        fmt: 輸出格式 ("pdf", "docx", "xlsx", "pptx")
        title: 文件標題
        html: HTML 字串（用於 pdf）
        sections: 段落列表 [{"heading": str, "body": str}]（用於 docx）
        tables: 表格列表 [{"name": str, "headers": [...], "rows": [[...]]}]（用於 xlsx）
        slides: 投影片列表 [{"title": str, "bullets": [...]}]（用於 pptx）
        output_dir: 輸出目錄（預設系統暫存）

    Returns:
        生成檔案的絕對路徑
    """
    fmt = fmt.lower().strip().lstrip(".")
    out = Path(output_dir) if output_dir else _OUTPUT_DIR
    out.mkdir(parents=True, exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = "".join(c for c in title if c.isalnum() or c in " _-")[:50].strip()
    filename = f"{safe_title}_{ts}.{fmt}" if safe_title else f"export_{ts}.{fmt}"
    filepath = out / filename

    if fmt == "pdf":
        _export_pdf(html, filepath, title, sections)
    elif fmt == "docx":
        _export_docx(filepath, title, sections or [])
    elif fmt == "xlsx":
        _export_xlsx(filepath, title, tables or [])
    elif fmt == "pptx":
        _export_pptx(filepath, title, slides or [])
    else:
        raise ValueError(f"Unsupported format: {fmt}. Use pdf/docx/xlsx/pptx.")

    logger.info(f"[Export] {fmt.upper()} generated: {filepath} ({filepath.stat().st_size} bytes)")
    return str(filepath)


# ─── PDF ───

def _export_pdf(
    html: str,
    filepath: Path,
    title: str,
    sections: Optional[List[Dict[str, str]]] = None,
) -> None:
    """HTML → PDF（使用 WeasyPrint，純 CPU）."""
    import weasyprint

    if not html and sections:
        html = _sections_to_html(sections, title)
    elif not html:
        html = f"<html><body><h1>{title}</h1><p>No content provided.</p></body></html>"

    weasyprint.HTML(string=html).write_pdf(str(filepath))


# ─── Word (docx) ───

def _export_docx(
    filepath: Path,
    title: str,
    sections: List[Dict[str, str]],
) -> None:
    """結構化內容 → Word 文件."""
    from docx import Document
    from docx.shared import Pt

    doc = Document()

    # 標題
    doc.add_heading(title, level=0)
    doc.add_paragraph(f"Generated by MUSEON · {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph("")

    for sec in sections:
        heading = sec.get("heading", "")
        body = sec.get("body", "")
        if heading:
            doc.add_heading(heading, level=1)
        if body:
            for para_text in body.split("\n"):
                stripped = para_text.strip()
                if not stripped:
                    continue
                if stripped.startswith("- ") or stripped.startswith("• "):
                    doc.add_paragraph(stripped[2:], style="List Bullet")
                else:
                    doc.add_paragraph(stripped)

    doc.save(str(filepath))


# ─── Excel (xlsx) ───

def _export_xlsx(
    filepath: Path,
    title: str,
    tables: List[Dict[str, Any]],
) -> None:
    """表格資料 → Excel."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill

    wb = Workbook()
    # 移除預設空工作表
    if wb.active and not tables:
        wb.active.title = title

    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="C4502A", end_color="C4502A", fill_type="solid")

    for i, table in enumerate(tables):
        sheet_name = table.get("name", f"Sheet{i+1}")[:31]
        if i == 0:
            ws = wb.active
            ws.title = sheet_name
        else:
            ws = wb.create_sheet(title=sheet_name)

        headers = table.get("headers", [])
        rows = table.get("rows", [])

        # 寫入標題行
        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=h)
            cell.font = header_font
            cell.fill = header_fill

        # 寫入資料行
        for row_idx, row_data in enumerate(rows, 2):
            for col_idx, val in enumerate(row_data, 1):
                ws.cell(row=row_idx, column=col_idx, value=val)

        # 自動調整欄寬
        for col in ws.columns:
            max_len = 0
            col_letter = col[0].column_letter
            for cell in col:
                val = str(cell.value) if cell.value else ""
                max_len = max(max_len, len(val))
            ws.column_dimensions[col_letter].width = min(max_len + 4, 50)

    wb.save(str(filepath))


# ─── PowerPoint (pptx) ───

def _export_pptx(
    filepath: Path,
    title: str,
    slides: List[Dict[str, Any]],
) -> None:
    """重點摘要 → PowerPoint."""
    from pptx import Presentation
    from pptx.util import Inches, Pt

    prs = Presentation()

    # 封面頁
    slide_layout = prs.slide_layouts[0]  # Title Slide
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = f"MUSEON · {datetime.now().strftime('%Y-%m-%d')}"

    # 內容頁
    bullet_layout = prs.slide_layouts[1]  # Title and Content
    for s in slides:
        slide = prs.slides.add_slide(bullet_layout)
        slide.shapes.title.text = s.get("title", "")

        body = slide.placeholders[1]
        tf = body.text_frame
        tf.clear()

        bullets = s.get("bullets", [])
        for i, bullet in enumerate(bullets):
            if i == 0:
                tf.text = bullet
            else:
                p = tf.add_paragraph()
                p.text = bullet

    prs.save(str(filepath))


# ─── Helper ───

def publish_document(
    fmt: str,
    *,
    title: str = "MUSEON Document",
    html: str = "",
    sections: Optional[List[Dict[str, str]]] = None,
    tables: Optional[List[Dict[str, Any]]] = None,
    slides: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """一鍵匯出 + 發佈到 GitHub Pages + 回傳公開連結.

    純 CPU（文件生成）+ shell（git push），零 token。

    Returns:
        GitHub Pages 公開 URL，失敗時回傳空字串
    """
    import subprocess

    filepath = export_document(
        fmt, title=title, html=html,
        sections=sections, tables=tables, slides=slides,
    )

    script = Path.home() / "MUSEON" / "scripts" / "workflows" / "publish-report.sh"
    if not script.exists():
        logger.error(f"[Export] publish script not found: {script}")
        return ""

    try:
        result = subprocess.run(
            ["bash", str(script), filepath],
            capture_output=True, text=True, timeout=300,
        )

        # 從輸出中提取 VERIFIED_URL
        for line in result.stdout.split("\n"):
            if line.startswith("VERIFIED_URL=") and len(line) > 14:
                url = line.split("=", 1)[1].strip()
                logger.info(f"[Export] published: {url}")
                return url

        logger.warning(f"[Export] publish completed but no VERIFIED_URL found")
        # 回傳預期 URL（可能 CDN 還沒到）
        filename = Path(filepath).name
        return f"https://zealchou.github.io/MUSEON/reports/{filename}"

    except subprocess.TimeoutExpired:
        logger.error("[Export] publish timed out (300s)")
        return ""
    except Exception as e:
        logger.error(f"[Export] publish failed: {e}")
        return ""


def _sections_to_html(sections: List[Dict[str, str]], title: str) -> str:
    """將 sections 轉成簡單 HTML（供 PDF 渲染）."""
    parts = [
        "<!DOCTYPE html><html><head>",
        '<meta charset="UTF-8">',
        "<style>",
        "body { font-family: 'Noto Sans TC', sans-serif; margin: 40px; line-height: 1.8; color: #12121A; }",
        "h1 { color: #C4502A; border-bottom: 2px solid #C4502A; padding-bottom: 8px; }",
        "h2 { color: #2A7A6E; margin-top: 24px; }",
        "ul { padding-left: 20px; }",
        "li { margin-bottom: 6px; }",
        "</style></head><body>",
        f"<h1>{title}</h1>",
    ]
    for sec in sections:
        heading = sec.get("heading", "")
        body = sec.get("body", "")
        if heading:
            parts.append(f"<h2>{heading}</h2>")
        if body:
            paragraphs = body.split("\n")
            for p in paragraphs:
                p = p.strip()
                if not p:
                    continue
                if p.startswith("- ") or p.startswith("• "):
                    parts.append(f"<ul><li>{p[2:]}</li></ul>")
                else:
                    parts.append(f"<p>{p}</p>")
    parts.append("</body></html>")
    return "\n".join(parts)
